/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import com.google.common.collect.Lists;
import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodney Rizo
 */
public class frmPrincipal extends javax.swing.JFrame {

    String q0;
    int fila_q0;
    List<String> lista_alf;
    List<String> lista_q;
    List<String> lista_qf;
    String[] array_alf;
    String[] array_q;
    String[] array_qf;
    transicion[][] trans;
    int n;
    int aux_ns;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransicion = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCadena = new javax.swing.JTextField();
        btnEvaluar = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFinalState = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Autómatas");

        jPanel1.setBackground(new java.awt.Color(40, 55, 71));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTransicion.setBackground(new java.awt.Color(86, 166, 174));
        tblTransicion.setForeground(new java.awt.Color(255, 255, 255));
        tblTransicion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTransicion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 610, 169));

        btnGenerar.setBackground(new java.awt.Color(40, 55, 71));
        btnGenerar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tabla2.png"))); // NOI18N
        btnGenerar.setText("Generar tabla");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadena");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtCadena.setBackground(new java.awt.Color(153, 153, 153));
        txtCadena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCadena.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 165, -1));

        btnEvaluar.setBackground(new java.awt.Color(40, 55, 71));
        btnEvaluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEvaluar.setForeground(new java.awt.Color(255, 255, 255));
        btnEvaluar.setText("Evaluar");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEvaluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 130, -1));

        txtResult.setBackground(new java.awt.Color(153, 153, 153));
        txtResult.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtResult.setForeground(new java.awt.Color(255, 255, 255));
        txtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultActionPerformed(evt);
            }
        });
        jPanel1.add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 100, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estado final");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        txtFinalState.setBackground(new java.awt.Color(153, 153, 153));
        txtFinalState.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFinalState.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtFinalState, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 100, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tabla de transiciones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingreso de datos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jButton1.setBackground(new java.awt.Color(40, 55, 71));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar cadena");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed

        int counterAlfabet = 0;
        int counterQf = 0;
        int counterQ = 0;
        int alfabetLength = 0;
        int finalStateLength = 0;
        int stateLength = 0;

        String filePath = "src\\files\\tabla.txt";

        File file = new File(filePath);

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columns = firstLine.split(";");
            DefaultTableModel model = (DefaultTableModel) tblTransicion.getModel();
            model.setColumnIdentifiers(columns);

            //Storing alfabet's length
            for (int i = 2; i < columns.length; i++) {
                alfabetLength++;
            }

            //Assigning length of alfabet
            array_alf = new String[alfabetLength];

            //Storing the alfabet
            for (int i = 2; i < columns.length; i++) {
                array_alf[counterAlfabet] = columns[i].toString();
                counterAlfabet++;
            }

            Object[] rows = br.lines().toArray();

            for (int i = 0; i < rows.length; i++) {
                String line = rows[i].toString().trim();
                String[] dataRow = line.split(";", -1);
                stateLength++; //Setting length of states array
                if (dataRow[1].equals("Si") || dataRow[1].equals("SI") || dataRow[1].equals("sI") || dataRow[1].equals("si")) {
                    finalStateLength++; //Setting length of final states array
                }
                for (int j = 2; j < columns.length; j++) {

                    //System.out.println(dataRow[j]);
                    if (dataRow[j].equals("-") || dataRow[j].equals("")) {
                        dataRow[j] = "";
                    }
                }
                model.addRow(dataRow);
            }

            //Assigning length of states array
            array_q = new String[stateLength];

            //Assigning length of final states array
            array_qf = new String[finalStateLength];

            //Storing final states
            for (int i = 0; i < rows.length; i++) {
                String line = rows[i].toString().trim();
                String[] dataRow = line.split(";");
                //Getting first state
                if (i == 0) {
                    q0 = dataRow[0];
                }
                //Getting states
                array_q[counterQ] = dataRow[0].trim();
                counterQ++;
                if (dataRow[1].equals("Si") || dataRow[1].equals("SI") || dataRow[1].equals("sI") || dataRow[1].equals("si")) {
                    //Getting final states
                    array_qf[counterQf] = dataRow[0].trim();
                    counterQf++;
                }
            }
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed

        String cadena = txtCadena.getText();

        if (cadena.equals(null) || "".equals(cadena)) {
            JOptionPane.showMessageDialog(null, "Inserte una cadena para evaluar", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        if (tblTransicion.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Genere la tabla antes de evaluar una cadena", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        lista_alf = Lists.newArrayList(array_alf);
        lista_q = Lists.newArrayList(array_q);
        lista_qf = Lists.newArrayList(array_qf);

        trans = new transicion[tblTransicion.getRowCount()][tblTransicion.getColumnCount() - 2];
        //System.out.println("rowCount ->" + tblTransicion.getRowCount() + "\nColumnCount ->" + tblTransicion.getColumnCount());
        for (int i = 0; i < trans.length; i++) {
            for (int j = 0; j < trans[i].length; j++) {
                if (tblTransicion.getValueAt(i, j + 2).toString().equals("null") || tblTransicion.getValueAt(i, j + 2).toString().equals("-") || tblTransicion.getValueAt(i, j + 2).toString().equals(" ")) {
                    trans[i][j] = new transicion(lista_q.get(i), lista_alf.get(j), null);
                } else {
                    trans[i][j] = new transicion(lista_q.get(i), lista_alf.get(j), tblTransicion.getValueAt(i, j + 2).toString());
                    //System.out.println("value at (" + i + "," + (j + 1) + ") -> " + tblTransicion.getValueAt(i, j + 2).toString());
                }
                if (lista_q.get(i).equals(q0)) {
                    fila_q0 = i;
                }
            }
        }

        String cad = txtCadena.getText(); //Stores value of the string to be tested
        char[] cad_rev = cad.toCharArray();
        List<String> lista_cad = new ArrayList<String>();
        for (char obj : cad_rev) {
            lista_cad.add(Character.toString(obj));
        }

        n = cad.length();
        aux_ns = 0;
        String next_state = null;
        boolean aceptado = true;
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < lista_alf.size(); j++) {
                if (trans[fila_q0][j].getLetra().equals(String.valueOf(cad.charAt(0)))) {
                    next_state = trans[fila_q0][j].getEstado_obj();
                    if (next_state == null) {
                        JOptionPane.showMessageDialog(null, "Imposible continuar, transicion inexistente");
                        aceptado = false;
                    } else {
                        for (int k = 0; k < lista_q.size(); k++) {
                            if (lista_q.get(k).equals(next_state)) {
                                fila_q0 = k;
                            }
                        }
                    }
                }
            }
            cad = cad.substring(1, cad.length());
            if (aceptado == false) {
                next_state = "error";
                break;
            }
        }
        for (int i = 0; i < lista_qf.size(); i++) {
            if (next_state.equals(lista_qf.get(i))) {
                Font f = txtResult.getFont();
                txtResult.setForeground(Color.green);
                txtResult.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
                txtResult.setText("Aceptado"); //color verde
                txtFinalState.setText(next_state);
                System.out.println("All good 😃");
                break;
            } else {
                Font f = txtResult.getFont();
                txtResult.setForeground(Color.red);
                txtResult.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
                txtResult.setText("Rechazado"); //color rojo
                txtFinalState.setText(next_state);
                System.out.println("Check the transitions 👀");
            }
        }

    }//GEN-LAST:event_btnEvaluarActionPerformed

    private void txtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtCadena.setText(null);
        txtResult.setText(null);
        txtFinalState.setText(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransicion;
    private javax.swing.JTextField txtCadena;
    private javax.swing.JTextField txtFinalState;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
